name: integration-test
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: integration-test
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clean work dir from previous runs
        run: |
          rm -rf *
      - name: setup go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.*'
        id: go
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ControllerIntegTest
      - name: setup env
        run: |
          source ~/.bashrc
      - name: make controller-gen
        run: make controller-gen
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup kind and run integration tests
        run: make integration-test
      - name: cleanup all the kind clusters
        run: make delete-all-kind-clusters
