name: prod-release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for this release (must already be pushed).'
        required: true

permissions:
  contents: read

jobs:
  prod-release:
    name: prod-release
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials (prod-BAH)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: me-south-1
          role-to-assume: ${{ secrets.PROD_BAH_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Configure AWS Credentials (prod-CPT)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: af-south-1
          role-to-assume: ${{ secrets.PROD_CPT_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Configure AWS Credentials (prod-HKG)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-east-1
          role-to-assume: ${{ secrets.PROD_HKG_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Configure AWS Credentials (prod-MXP)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-south-1
          role-to-assume: ${{ secrets.PROD_MXP_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Configure AWS Credentials (prod-BJS)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: cn-north-1
          role-to-assume: ${{ secrets.PROD_BJS_AWS_ROLE }}
          role-session-name: ControllerProdRelease
      - name: Configure AWS Credentials (prod-ZHY)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: cn-northwest-1
          role-to-assume: ${{ secrets.PROD_ZHY_AWS_ROLE }}
          role-session-name: ControllerProdRelease
